#!/bin/bash
#
# COMAND LINE INTERFACE WIKI
#
# Criado por: Edegard Santos.
# 06/10/2016
#
#
## BASHCSS
trap 'menu'  1 2 3 15 20
BLACK='\E[0;30m'   # PRETO
BOLD='\033[37;4;1m' # NEGRITO
UND='\033[37;4m' # SUBLINHADO
RED='\033[00;31m' # VERMELHO
GREEN='\033[01;32m' # VERDE
YELLOW='\033[01;33m' # AMARELO
BLUE='\033[01;34m' # AZUL
PURPLE='\033[00;35m' # ROXO
CYAN='\033[00;36m' # CIANO
LIGHTGRAY='\033[00;37m' # CINZA CLARO
LRED='\033[01;31m' # VERMELHO CLARO
LGREEN='\033[01;32m' # VERDE CLARO
LYELLOW='\033[01;33m' # AMARELO CLARO
LBLUE='\033[01;34m' # AZUL CLARO
LPURPLE='\033[01;35m' # ROXO CLARO
LCYAN='\033[01;36m' # CIANO CLARO
WHITE='\033[01;37m' # BRANCO
RESE=$(tput sgr0) # SEM COR
#
# Cabeçalho
#
cab() {
clear
printf "##############################################
                   ${LCYAN}WEBHOSTING${RESE}
      ${LYELLOW}COMMAND ${LBLUE}LINE ${LYELLOW}INTERFACE ${LBLUE}WIKI ${GREEN}(H${YELLOW}G${BLUE}B${WHITE}R)${RESE}
##############################################\n"
}
menu() {
cab
printf "[ 1 ] E-mail            [ 2 ] DNS               [ 3 ] cPanel            
[ 4 ] Shell             [ 5 ] TOS               [ 6 ] Outro - Pesquisar\n"
read -n 1 -p "Opcao: <Enter=Sair>" opc
[ "x$opc" == "x" ] && clear && echo -e "\nWiki finalizada, valor inválido\n" && exit 1
case $opc in
        1) echo -e "\nBotão 1 apertado"
           ;;
        2) echo -e "\nBotão 2 Apertado"
           ;;
        3) echo -e "\nBotão 3 Apertado"
           ;;
        4) echo -e "\nBotão 4 Apertado"
           ;;
        5) echo -e "\nBotão 5 Apertado"
           ;;
        6) echo -e "\nBotão 6 Apertado"
           ;;
esac
}
# Chamar Menu
menu

